apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: labforge
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/OWNER/labforge:1.0.0
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
