apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: labforge
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/name: labforge