apiVersion: v1
kind: Service
metadata:
  name: labforge
  namespace: labforge
  labels:
    app.kubernetes.io/name: labforge
    app.kubernetes.io/part-of: labforge
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: labforge